name: Despliegue

on:
  push:
    branches:
      - dev
      - master
    
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRETS_ACCESS_KEY }}'

jobs:
  terraform :
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Permisos para crear issues
    steps: 
      - name: clone_repo
        uses: actions/checkout@v3

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.9.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: set_environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]
          then
            echo "Entorno productivo"
            echo "environment=prod" >> $GITHUB_ENV
            echo "tf_vars_file=prod.tfvars" >> $GITHUB_ENV
          else
            echo "Entorno desarrollo"
            echo "environment=dev" >> $GITHUB_ENV
            echo "tf_vars_file=dev.tfvars" >> $GITHUB_ENV
          fi

      - name: terraform_init
        run: |
          terraform init

      - name: select_workspace
        run: |
          terraform workspace select -or-create $environment

      - name: terraform_plan
        run: |
          terraform plan -var-file $tf_vars_file

      - name: manual_approval
        if: env.environment == "prod"
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: pedrofenix19
          minimum-approvals: 1
          issue-title: "Despliegue final"
          issue-body: "Por favor aprobar el despliegue"
            
      - name: terraform_apply
        run: |
          terraform apply -var-file $tf_vars_file -auto-approve

  