name: Despliegue

on:
  push:
    branches:
      - dev
      - master
    
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRETS_ACCESS_KEY }}'

jobs:
  terraform :
    runs-on: ubuntu-latest
    steps: 
      - name: clone_repo
        uses: actions/checkout@v3

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.9.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: set_environment
        run: |
          if [[ "${{ github.ref }}" == "refs/head/master" ]]
          then
            echo "Entorno productivo"
            export environment="prod"
          else
            echo "Entorno desarrollo"
            export environment="dev"
          fi

      - name: terraform_init
        run: |
          terraform init

      - name: select_workspace
        run: |
          if [[ "${{ github.ref }}" == "refs/head/master" ]]
          then
            terraform workspace select prod -or-create
          else
            terraform workspace select dev -or-create
          fi

      - name: terraform_plan
        run: |
          if [[ "${{ github.ref }}" == "refs/head/master" ]]
          then
            terraform plan -var-file prod.tfvars
          else
            terraform plan -var-file dev.tfvars
          fi
            
      - name: terraform_apply
        run: |
          if [[ "${{ github.ref }}" == "refs/head/master" ]]
          then
            terraform apply -var-file prod.tfvars -auto-approve
          else
            terraform apply -var-file dev.tfvars -auto-approve
          fi

  